name: vidmeet
description: "VidMeet - A modern video social media app"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  image_picker: '>=1.1.2'
  file_picker: '>=8.1.2'
  timeago: ^3.7.0
  flutter_local_notifications: ^17.2.2
  url_launcher: ^6.0.0
  package_info_plus: ^8.0.0
  http: ^1.0.0
  shared_preferences: ^2.0.0
  geolocator: 13.0.4
  dio: ^5.0.0
  socket_io_client: ^3.0.0
  sqflite: ^2.0.0
  connectivity_plus: ^6.0.0
  firebase_core: ^3.5.0
  firebase_messaging: ^15.1.2
  device_info_plus: ^10.1.2
  fluttertoast: ^8.2.12
  geocoding: ^3.0.0
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  permission_handler: ^11.0.0
  drift: ^2.28.1
  sqlite3_flutter_libs: ^0.5.0
  event_bus: ^2.0.0
  intl: ^0.19.0
  chewie: ^1.11.3
  visibility_detector: ^0.4.0+2
  better_player_plus: ^1.0.8
  google_sign_in: ^6.2.2
  firebase_auth: ^5.7.0
  sign_in_with_apple: ^7.0.1
  applovin_max: ^4.5.2
  flutter_svg: ^2.2.0
  google_mobile_ads: ^6.0.0
  video_thumbnail: ^0.5.6
  share_plus: ^10.1.4
  path_provider: ^2.1.5
  flutter_switch: ^0.3.2
  android_id: ^0.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.18.0
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.4

flutter:
  uses-material-design: true
  assets:
    - legal/
    - assets/icon/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/vidmeet_icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#D1F244"
  color_dark: "#D1F244"
  image: "assets/icon/splash_screen_icon.png"
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center

  android_12:
    image: "assets/icon/splash_screen_icon.png"
    icon_background_color: "#D1F244"
    image_dark: "assets/icon/splash_screen_icon.png"
    icon_background_color_dark: "#D1F244"
    color: "#D1F244"
